-- ============================================================================
-- exportTableDefinition サンプルDDL（Oracle）
--
-- PostgreSQL版（docs/sample/postgres/ddl.sql）と同じスキーマ構成をOracleで作るDDLです。
-- 出力対象となりうるオブジェクト種別（テーブル／ビュー／マテリアライズドビュー／インデックス／制約／外部キー／
-- シーケンス／トリガー／関数・プロシージャ・パッケージ／ユーザー定義型（オブジェクト型・コレクション型）／パーティション表）と、
-- ER図の多重度パターン（1対1・0..1対1・1対多・0..1対多・多対多・自己参照・複合外部キー・関連なし）を
-- PostgreSQL版と同じテーブル・列で一通り含めています。
--
-- PostgreSQL版との主な違い:
--   * スキーマはユーザーとして作る。名前は大文字で格納される（SAMPLE.EMPLOYEE等）
--   * 名前を付けない制約にはSYS_C...の名前が振られ、流し込むたびに変わる。出力をベースラインと比べるため、
--     主キー・一意・外部キー・CHECK制約に、PostgreSQLが自動で付ける名前と同じ名前を付ける（NOT NULLは制約として出力されない）
--   * serial → IDENTITY列、ENUM型 → CHECK制約、DOMAIN型 → 型＋CHECK制約、jsonb → CLOB＋IS JSON、
--     GIN索引 → JSON_VALUEの関数索引、オーバーロード関数 → パッケージ、TRUNCATEトリガー → 文単位のDELETEトリガー、
--     多段・DEFAULT・別スキーマのパーティション → MAXVALUEのパーティション（多段に当たるサブパーティションは、
--     パーティションごとに名前を付けないとSYS_SUBP...の名前が振られるため、結合テストの中で確かめる）、
--     RANGE型 → コレクション型（VARRAY）
--
-- SQL*PlusにSYSDBA等の権限を持つユーザーでPDBへ接続して流し込みます（ユーザーの作成から行うため）。
-- 実行後、SAMPLEユーザーで接続し、conf/config.yml の target.schemas に [SAMPLE] を指定して
-- 実行すると出力結果を確認できます。
-- ============================================================================

whenever sqlerror exit failure

/*
 * スキーマ（ユーザー）作成
 */
create user sample identified by sample quota unlimited on users;
grant create session, create table, create view, create materialized view, create sequence,
    create trigger, create procedure, create type to sample;

-- 別スキーマに同名のテーブル（SAMPLE.DEPARTMENT）を置き、スキーマごとに取り違えず取得できるかを確かめる
create user sample_archive identified by sample_archive quota unlimited on users;

/*
 * 型定義（PostgreSQLのCOMPOSITE型に当たるオブジェクト型と、コレクション型）
 */
create type sample.address_type as object (
    street varchar2(100),
    city varchar2(50),
    postal_code varchar2(10)
);
/

create type sample.phone_number_list as varray(5) of varchar2(20);
/

/*
 * シーケンス
 */
-- どの列にも紐付かない独立したシーケンス
create sequence sample.invoice_no_seq
    increment by 1
    minvalue 1000
    maxvalue 999999
    start with 1000
    cache 5
    cycle;

/*
 * DDL作成（テーブル）
 */
-- 親テーブル（コメントは付与しない）
create table sample.department (
    department_id number(10) generated by default as identity constraint department_pkey primary key,
    department_code varchar2(10) not null
        constraint department_department_code_key unique,
    department_name varchar2(50) not null
);

-- 単独テーブル（他のテーブルと参照関係を持たない）
create table sample.parking_spot (
    parking_spot_id number(10) generated by default as identity constraint parking_spot_pkey primary key,
    spot_code varchar2(10) not null
        constraint parking_spot_spot_code_key unique
);

-- 1対多（必須）：department → employee
-- 0..1対多（任意・自己参照）：employee.manager_id → employee
-- 0..1対1（任意・一意）：parking_spot → employee.parking_spot_id
create table sample.employee (
    employee_id number(10) generated by default as identity constraint employee_pkey primary key,
    employee_code varchar2(10) not null
        constraint employee_employee_code_key unique,
    employee_name varchar2(50) not null,
    department_id number(10) not null
        constraint employee_department_id_fkey references sample.department(department_id),
    manager_id number(10)
        constraint employee_manager_id_fkey references sample.employee(employee_id),
    parking_spot_id number(10)
        constraint employee_parking_spot_id_key unique
        constraint employee_parking_spot_id_fkey references sample.parking_spot(parking_spot_id),
    status varchar2(10) default 'ACTIVE' not null
        constraint employee_status_check check (status in ('ACTIVE', 'ON_LEAVE', 'RETIRED')),
    salary number(10, 2) default 0 not null
        constraint employee_salary_check check (salary >= 0),
    profile clob default '{}' not null
        constraint employee_profile_check check (profile is json),
    hired_date date default trunc(sysdate) not null,
    updated_at timestamp default systimestamp not null
);

-- 1対1（必須）：employee ⇔ employee_profile（PKがそのままFK）
create table sample.employee_profile (
    employee_id number(10) constraint employee_profile_pkey primary key
        constraint employee_profile_employee_id_fkey references sample.employee(employee_id),
    address sample.address_type,
    emergency_contact varchar2(50),
    notes clob
);

create table sample.project (
    project_id number(10) generated by default as identity constraint project_pkey primary key,
    project_code varchar2(10) not null
        constraint project_project_code_key unique,
    project_name varchar2(100) not null,
    budget number(12, 2) constraint project_budget_check check (budget >= 0)
);

-- 多対多：project ⇔ employee（複合主キー＝2本の1対多外部キーの組み合わせ）
create table sample.project_assignment (
    project_id number(10) not null
        constraint project_assignment_project_id_fkey references sample.project(project_id),
    employee_id number(10) not null
        constraint project_assignment_employee_id_fkey references sample.employee(employee_id),
    role varchar2(30) default 'MEMBER' not null,
    assigned_at date default trunc(sysdate) not null,
    constraint project_assignment_pkey primary key (project_id, employee_id)
);

create table sample.warehouse_zone (
    warehouse_code varchar2(5) not null,
    zone_code varchar2(5) not null,
    zone_name varchar2(50) not null,
    constraint warehouse_zone_pkey primary key (warehouse_code, zone_code)
);

-- 1対多（必須・複合外部キー）：warehouse_zone → shipment
create table sample.shipment (
    shipment_id number(10) generated by default as identity constraint shipment_pkey primary key,
    warehouse_code varchar2(5) not null,
    zone_code varchar2(5) not null,
    shipped_at timestamp default systimestamp not null,
    constraint shipment_warehouse_code_zone_code_fkey foreign key (warehouse_code, zone_code)
        references sample.warehouse_zone(warehouse_code, zone_code)
);

-- 単独テーブル（関連なし。トリガーからの書き込み先）
create table sample.audit_log (
    log_id number(19) generated by default as identity constraint audit_log_pkey primary key,
    table_name varchar2(50) not null,
    record_id integer,
    action varchar2(10) not null
        constraint audit_log_action_check check (action in ('INSERT', 'UPDATE', 'DELETE')),
    changed_at timestamp default systimestamp not null,
    changed_by varchar2(50)
);

-- パーティション表（月次のレンジパーティション）。PostgreSQLのDEFAULTパーティションの代わりにMAXVALUEのパーティションを持つ
create table sample.attendance (
    attendance_id number(19) not null,
    work_date date not null,
    employee_id number(10) not null
        constraint attendance_employee_id_fkey references sample.employee(employee_id),
    work_minutes integer,
    constraint attendance_pkey primary key (attendance_id, work_date)
)
partition by range (work_date) (
    partition attendance_2025 values less than (date '2026-01-01'),
    partition attendance_2026_01 values less than (date '2026-02-01'),
    partition attendance_2026_02 values less than (date '2026-03-01'),
    partition attendance_2026_03 values less than (date '2026-04-01'),
    partition attendance_default values less than (maxvalue)
);

-- 別スキーマに同名のテーブル（SAMPLE.DEPARTMENT）があっても、索引・カラム等は取り違えず、スキーマごとに取得する
create table sample_archive.department (
    archive_id number(10) constraint department_pkey primary key,
    note varchar2(50)
);
create index sample_archive.idx_archive_department_note on sample_archive.department (note);
-- ALL_*のディクショナリビューには、接続ユーザーが権限を持つオブジェクトだけが現れる
grant select on sample_archive.department to sample;

-- パーティション表を参照するテーブル
create table sample.attendance_note (
    note_id number(10) generated by default as identity constraint attendance_note_pkey primary key,
    attendance_id number(19) not null,
    work_date date not null,
    note clob,
    constraint attendance_note_attendance_id_work_date_fkey foreign key (attendance_id, work_date)
        references sample.attendance(attendance_id, work_date)
);

/*
 * ビュー
 */
create view sample.employee_directory_view as
    select
        e.employee_id,
        e.employee_code,
        e.employee_name,
        d.department_name,
        e.status
    from sample.employee e
    join sample.department d on e.department_id = d.department_id;

-- ビュー・パーティション表・出力対象外のスキーマのテーブルを参照するビュー
create view sample.attendance_monthly_view as
    select
        dv.department_name,
        trunc(a.work_date, 'MM') as work_month,
        sum(a.work_minutes) as total_minutes,
        max(ad.note) as archive_note
    from sample.attendance a
    join sample.employee_directory_view dv on dv.employee_id = a.employee_id
    left join sample_archive.department ad on ad.note = dv.department_name
    group by dv.department_name, trunc(a.work_date, 'MM');

/*
 * マテリアライズドビュー
 */
create materialized view sample.project_summary_mv as
    select
        p.project_id,
        p.project_name,
        count(pa.employee_id) as member_count
    from sample.project p
    left join sample.project_assignment pa on pa.project_id = p.project_id
    group by p.project_id, p.project_name;

/*
 * インデックス（B木以外の索引種別として関数索引・複合索引・マテビューへの索引も含める）
 */
create index sample.idx_employee_department_status on sample.employee (department_id, status);
create index sample.idx_employee_profile_skill on sample.employee (json_value(profile, '$.skill' returning varchar2(50)));
create unique index sample.project_summary_mv_pkey on sample.project_summary_mv (project_id);
-- パーティション表のローカル索引（パーティションごとに分割される）
create index sample.idx_attendance_employee on sample.attendance (employee_id) local;

/*
 * トリガー（BEFORE / AFTER / INSTEAD OF、ROW / STATEMENT を一通り網羅）
 */
create or replace trigger sample.trg_employee_set_updated_at
    before update on sample.employee
    for each row
begin
    :new.updated_at := systimestamp;
end;
/

create or replace trigger sample.trg_employee_audit
    after insert or update or delete on sample.employee
    for each row
declare
    v_action varchar2(10);
begin
    v_action := case when inserting then 'INSERT' when updating then 'UPDATE' else 'DELETE' end;
    insert into sample.audit_log(table_name, record_id, action, changed_by)
    values ('employee', coalesce(:new.employee_id, :old.employee_id), v_action, user);
end;
/

-- OracleのTRUNCATEトリガーはスキーマ単位のDDLトリガーになるため、文単位のDELETEトリガーで代える
create or replace trigger sample.trg_project_assignment_delete
    after delete on sample.project_assignment
begin
    dbms_output.put_line('sample.project_assignment was deleted');
end;
/

create or replace trigger sample.trg_employee_directory_insert
    instead of insert on sample.employee_directory_view
    for each row
declare
    v_department_id number(10);
begin
    select department_id into v_department_id
    from sample.department
    where department_name = :new.department_name;

    insert into sample.employee(employee_code, employee_name, department_id)
    values (:new.employee_code, :new.employee_name, v_department_id);
end;
/

create or replace trigger sample.trg_attendance_check_work_minutes
    before insert or update on sample.attendance
    for each row
begin
    if :new.work_minutes < 0 then
        raise_application_error(-20001, 'work_minutes must not be negative');
    end if;
end;
/

/*
 * 関数・プロシージャ（Oracleでオーバーロードできるのはパッケージ内のサブプログラムだけのため、パッケージにまとめる）
 */
create or replace package sample.bonus as
    function calculate_bonus(p_salary number, p_rate number) return number deterministic;
    function calculate_bonus(p_salary number) return number deterministic;
end bonus;
/

create or replace package body sample.bonus as
    function calculate_bonus(p_salary number, p_rate number) return number deterministic is
    begin
        return p_salary * p_rate;
    end;

    function calculate_bonus(p_salary number) return number deterministic is
    begin
        return calculate_bonus(p_salary, 0.1);
    end;
end bonus;
/

create or replace procedure sample.raise_salary(p_employee_id number, p_amount number) as
begin
    update sample.employee set salary = salary + p_amount where employee_id = p_employee_id;
end;
/

/*
 * コメント（論理名）
 * employeeとprojectはDBコメントで論理名を付与し、departmentは無コメントのままにしている
 */
comment on table sample.employee is '従業員';
comment on column sample.employee.employee_id is '従業員ID';
comment on column sample.employee.employee_code is '従業員コード';
comment on column sample.employee.employee_name is '従業員名';
comment on column sample.employee.department_id is '所属部署ID';
comment on column sample.employee.manager_id is '上長の従業員ID';
comment on column sample.employee.parking_spot_id is '駐車場ID';
comment on column sample.employee.status is '在籍状況';
comment on column sample.employee.salary is '給与';
comment on column sample.employee.profile is 'プロフィール（JSON）';
comment on column sample.employee.hired_date is '入社日';
comment on column sample.employee.updated_at is '更新日時';

comment on table sample.project is 'プロジェクト';
comment on column sample.project.project_id is 'プロジェクトID';
comment on column sample.project.project_code is 'プロジェクトコード';
comment on column sample.project.project_name is 'プロジェクト名';
comment on column sample.project.budget is '予算';

comment on materialized view sample.project_summary_mv is 'プロジェクト別要員数集計';
comment on table sample.attendance_monthly_view is '部署別の月次勤務時間';

comment on table sample.attendance is '勤怠（月次パーティション）';
comment on column sample.attendance.work_date is '勤務日（パーティションキー）';
comment on column sample.attendance.work_minutes is '勤務時間（分）';

exit
